export const DEFAULT_TEACHER_CONFIG = {
  nominalResistance: 50,
  resistorOptions: [10, 20, 50, 100],
  voltageMin: 0,
  voltageMax: 10,
  voltageStep: 0.5,
  measurementNoise: true,
  noiseMagnitude: 0.012, // 1.2% realistic lab meter variation
  hintsEnabled: true,
  minReadingsRequired: 5,
  passingScore: 60,
};

export const APPARATUS_LIST = [
  {
    id: 'battery',
    name: 'Regulated DC Power Supply',
    symbol: '—||—',
    purpose: 'Provides an adjustable, steady electrical potential difference (Voltage) across the circuit.',
    connectionMethod: 'Connect the (+) positive terminal to the circuit switch/input and the (-) negative terminal to complete the return path.',
    specs: '0 – 10.0 V DC, high stability, overload safety protection.',
    iconName: 'BatteryCharging',
    keyRule: 'Always ensure voltage is zero or switch is OPEN before rewiring.',
  },
  {
    id: 'resistor',
    name: 'Standard Wire-Wound Resistor',
    symbol: '—/\\/\\/\\—',
    purpose: 'Provides a known constant ohmic electrical resistance opposing charge flow, dissipating heat predictably.',
    connectionMethod: 'Connected in series with the power supply and ammeter; connected in parallel with the voltmeter.',
    specs: 'Available: 10 Ω, 20 Ω, 50 Ω, 100 Ω (±1% tolerance, 5W ceramic rating).',
    iconName: 'Cpu',
    keyRule: 'Follows Ohm\'s Law V = IR strictly at constant temperature.',
  },
  {
    id: 'ammeter',
    name: 'Precision DC Ammeter',
    symbol: '—( A )—',
    purpose: 'Measures the rate of electric charge flow (Current in Amperes) passing through the circuit branch.',
    connectionMethod: 'MUST be connected in SERIES with the circuit loop so all current traverses its internal coil.',
    specs: '0.00 – 1.00 A DC (Dual analog needle + 7-segment digital display, internal resistance < 0.05 Ω).',
    iconName: 'Gauge',
    keyRule: 'NEVER connect directly across a power supply or in parallel — it causes a short circuit!',
  },
  {
    id: 'voltmeter',
    name: 'Precision DC Voltmeter',
    symbol: '—( V )—',
    purpose: 'Measures the potential difference (Voltage in Volts) between two distinct points across a component.',
    connectionMethod: 'MUST be connected in PARALLEL directly across the terminals of the resistor.',
    specs: '0.00 – 10.00 V DC (Dual analog needle + digital LCD, input impedance > 10 MΩ).',
    iconName: 'Activity',
    keyRule: 'NEVER connect in series in the main line, as its high resistance will block current.',
  },
  {
    id: 'switch',
    name: 'One-Way Plug / Knife Switch',
    symbol: '—/ —',
    purpose: 'Safely makes or breaks the electrical continuity of the closed circuit loop.',
    connectionMethod: 'Inserted in series in the positive power rail to isolate current immediately when open.',
    specs: 'Heavy-duty brass blade with insulated knob, positive tactile contact.',
    iconName: 'ToggleRight',
    keyRule: 'Keep switch OPEN during circuit assembly and adjustments.',
  },
  {
    id: 'wire',
    name: 'Insulated Banana Connecting Wires',
    symbol: '————',
    purpose: 'Conducts charge between terminal posts with near-zero wire resistance (<0.001 Ω).',
    connectionMethod: 'Click and drag from one terminal post to another to establish secure contact.',
    specs: 'Flexible copper braid, high-dielectric silicone sheath, spring-loaded banana pins.',
    iconName: 'Share2',
    keyRule: 'Red wires for positive rails, black wires for negative return, cyan for signal sensing.',
  }
];

export const CHALLENGE_SCENARIOS = [
  {
    id: 'challenge-1',
    title: 'Challenge 1: Target Current Verification',
    scenario: 'You are tasked with measuring the current through a 100 Ω resistor powered by a 5.0 V DC supply. Assemble the circuit and verify the exact expected current reading.',
    targetResistance: 100,
    targetVoltage: 5.0,
    expectedCurrent: 0.05,
    completionCriteria: 'Assemble circuit correctly, adjust voltage to 5.0 V, select 100 Ω resistor, and record reading.',
  },
  {
    id: 'challenge-2',
    title: 'Challenge 2: Mystery Resistance Determination',
    scenario: 'An unknown resistor is installed. With the power supply set to 4.0 V, your ammeter registers exactly 0.080 A. Determine the resistance using Ohm\'s Law calculation.',
    targetResistance: 50,
    targetVoltage: 4.0,
    expectedCurrent: 0.08,
    completionCriteria: 'Calculate R = V / I = 4.0 / 0.080 = 50 Ω correctly.',
  },
  {
    id: 'challenge-3',
    title: 'Challenge 3: Voltmeter Anomaly Troubleshooting',
    scenario: 'The laboratory technician reported that the circuit switch is closed, current is flowing through the ammeter, but the voltmeter stubbornly reads 0.00 V. Diagnose and resolve the connection fault.',
    targetResistance: 50,
    targetVoltage: 6.0,
    expectedCurrent: 0.12,
    faultType: 'open_voltmeter',
    completionCriteria: 'Identify that the voltmeter was disconnected from the resistor and rewire it in parallel across terminals A and B.',
  },
  {
    id: 'challenge-4',
    title: 'Challenge 4: Hazardous Overcurrent / Short Circuit',
    scenario: 'An emergency circuit breaker trip occurred due to an ammeter placed improperly in parallel across the power supply. Correct the wiring to safe series configuration.',
    targetResistance: 20,
    targetVoltage: 3.0,
    expectedCurrent: 0.15,
    faultType: 'short',
    completionCriteria: 'Rewire ammeter into series configuration with the resistor.',
  }
];
